/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";

import { Header } from "@/components/Header";
import { SVGFilters } from "@/components/SVGFilters";
import "./globals.css";

export const metadata: Metadata = {
  title: "Suburbia Sultanpur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bowlby+One+SC&family=DM+Mono:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet" />
        <style dangerouslySetInnerHTML={{
          __html: `
            :root {
              --font-bowlby-sc: "Bowlby One SC", sans-serif;
              --font-dm-mono: "DM Mono", monospace;
            }
          `
        }} />
      </head>
      <body
        className={`antialiased font-mono font-medium text-zinc-800`}
        suppressHydrationWarning
      >
        <main className="">
        <Header/>
        </main>
        {children}
        <SVGFilters>

        </SVGFilters>

      </body>
    </html>
  );
}
